version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:8000"  # Laravel uygulamasının portu
        volumes:
            - .:/var/www
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:r+3EOrGeZqM5H2v1qe0Z6/l8tGfjLkX+Tg9G2WU/0rI=
        networks:
            - laravel_network
        depends_on:
            - mysql
    nginx:
        image: nginx:stable-alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"  # Nginx'i 8080 portuna yönlendiriyoruz
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 243818Tt.
            MYSQL_DATABASE: blog
            MYSQL_PASSWORD: 243818Tt.
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel_phpmyadmin
        ports:
            - "8081:80"  # PhpMyAdmin'ı 8081 portuna yönlendiriyoruz
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: 243818Tt.
            PHP_UPLOAD_LIMIT: 300M
            PHP_MEMORY_LIMIT: 512M
            PMA_ABSOLUTE_URI: http://localhost:8081  # PhpMyAdmin için URL
        depends_on:
            - mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    dbdata:
